backend:
  name: github
  repo: brianmcdonald/www-miriamdenardi # Path to your Github repository
  branch: master # Branch to update

media_folder: "static//uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads